packages:
  - "core"
  - "py/correctness"
  - "js/packages/browser-tests"
  - "js/packages/crsqlite-wasm"
  - "js/packages/node-allinone"
  - "js/packages/node-tests"
  - "js/packages/p2p"
  - "js/packages/react"
  - "js/packages/direct-connect-browser"
  - "js/packages/direct-connect-common"
  - "js/packages/direct-connect-nodejs"
  - "js/packages/rx-query"
  - "js/packages/rx-tbl"
  - "js/packages/xplat-api"
  - "js/packages/xplat-tests"
  - "js/packages/sandbox"
  - "js/packages/sandbox-node"
  - "js/tsbuild-all"
  - "js/deps/wa-sqlite"
  - "js/deps/dyu/wa-sqlite"
